<?php
    $form->setAttribute('action', $this->url('student', array('action' => 'add')));
    $form->prepare();
?>
<h1>Edit User</h1>

<?php echo $this->form()->openTag($form); ?>

<?php echo $this->formHidden($form->get('id')); ?>
<div class="row">
    <div class="col-md-12">
    <?php echo $this->formRow($form->get('name')); ?>
    </div>
    <div class="col-md-12">
    <?php echo $this->formSubmit($form->get('send')); ?>
    </div>
</div>

<?php echo $this->form()->closeTag(); ?>
