<div id="highchart" style="min-width: 310px; height: 400px; margin: 0 auto"></div>


<script type="text/javascript">
	$(function () {
    $('#highchart').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'Monthly Average Rainfall'
        },
        subtitle: {
            text: 'Source: WorldClimate.com'
        },
        xAxis: {
            categories: [
                <?php 
                	foreach ($json->labels as $label) {
                		# code...
                		echo "'" . $label . "',";
                	}
                 ?>
            ],
            crosshair: true
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Rainfall (mm)'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [
        <?php 
            	foreach ($json->datasets as $key => $dataset) {
            		echo "{name: '" . 
            		$key . 
            		"',data: [";
            		foreach ($dataset as $data) {
            			echo $data . ",";
            		}
            		echo "]},";
            	}
        ?>
        ]
    });
});

</script>