<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
	<body>
		<div class="jumbotron">
		<h1>List of Profiles</h1>
		</div>
		
		<div class="row">
		    <div class="col-md-12 text-right">
		        <a href="<?php echo $this->url('profile', ['action'=>'add']); ?>" class="btn btn-info" role="button">Add</a>
		    </div>
		</div>
			<?php foreach($profiles as $profile):?>
			
			<div class="row">
			    <div class="col-md-4">
			        <a href="<?php echo $this->url('profile', ['action'=>'get', 'id'=>$profile->id]); ?>">
			        <?php echo $profile->name; ?>
			        </a>
			    </div>
			    <div class="col-md-4">
			        <?php echo $profile->address; ?>
			    </div>
			    <div class="col-md-4 text-right">
			    	<a href="<?php echo $this->url('profile', ['action'=>'edit', 'id'=>$profile->id]); ?>" class="btn btn-info" role="button">Edit</a>
			        <a href="<?php echo $this->url('profile', ['action'=>'delete', 'id'=>$profile->id]); ?>" class="btn btn-danger" role="button">Delete</a>
			    </div>
			</div>
			<?php endforeach; ?>
	</body>
</html>
